export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const ADD_NOOB = "ADD_NOOB";
export const TOGGLE_NOOB = "TOGGLE_NOOB";
export const ADD_NOOB_POINT = "ADD_NOOB_POINT";
export const ADD_ASSASSIN_POINT = "ADD_ASSASSIN_POINT";
export const ADD_NOOB_TEXT_CHANGED = "ADD_NOOB_TEXT_CHANGED";
