export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const ADD_NOOB = "ADD_NOOB";
export const TOGGLE_NOOB = "TOGGLE_NOOB";
export const ADD_NOOB_POINT = "ADD_NOOB_POINT";
export const ADD_ASSASSIN_POINT = "ADD_ASSASSIN_POINT";
export const ADD_NOOB_TEXT_CHANGED = "ADD_NOOB_TEXT_CHANGED";
export const LOAD_NOOBS_SUCCESS = "LOAD_NOOBS_SUCCESS";
export const LOAD_NOOB_SUCCESS = "LOAD_NOOB_SUCCESS";
